export const booksHu = {
  catalogTitle: "Könyvek",
  catalogEmpty: "Jelenleg nincs elérhető könyv.",
  catalogError: "A bolt átmenetileg nem elérhető. Próbáld újra később.",
  retry: "Újra",
  formatPhysical: "Nyomtatott",
  formatEbook: "E-könyv",
  buy: "Vásárlás",
  viewBook: "Könyv megtekintése",
  author: "Szerző",
  unavailable: "Nem elérhető",
  notFound: "A könyv nem található.",
  backToCatalog: "Vissza a könyvekhez",
  alsoAvailableAs: "Elérhető más formátumban is:",
};
